# This is a basic workflow to help you get started with Actions

name: BILIBILI-HELPER

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron: '50 10 * * *'
    # cron表达式，Actions时区是UTC时间，所以下午18点要往前推8个小时

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Clone repo from JunzhouLiu/BILIBILI-HELPER
        uses: actions/checkout@v2
        with:
          repository: JunzhouLiu/BILIBILI-HELPER
          path: work
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          BILI_JCT: ${{ secrets.BILI_JCT }}
          DEDEUSERID: ${{ secrets.DEDEUSERID }}
          SESSDATA: ${{ secrets.SESSDATA }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run: |
          cp BILIBILI-HELPER/config.json work/src/main/resources/config.json
          cd work
          mvn compile exec:java -Dexec.mainClass="top.misec.BiliMain" -Dexec.args="${DEDEUSERID} ${SESSDATA} ${BILI_JCT} ${SERVERPUSHKEY}"
